"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
									1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def f(maxV):
	a,b = 0,1
	yield a
	yield b
	while a+b < maxV:
		a,b = b, a+b
		yield b

print sum([x for x in f(4000000) if x % 2 == 0])

# 		  n-1  n-2
# fib(1) = 1  + 0	= 1
# fib(2) = 1  + 1 	= 2
# fib(3) = 2  + 1	= 3
# fib(4) = 3  + 2 	= 5
# fib(5) = 5  + 3 	= 8
# fib(6) = 8  + 5 	= 13
# fib(7) = 13 + 8 	= 21
# fib(8) = 21 + 13 	= 34
# fib(9) = 34 + 21 	= 55
# fib(10)= 55 + 34 	= 89 